//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class City
    {
        public City()
        {
            this.EmployeeLocations = new HashSet<EmployeeLocation>();
        }
    
        public System.Guid CityID { get; set; }
        public string City1 { get; set; }
        public Nullable<System.Guid> CountryOfficeID { get; set; }
    
        public virtual CountryOffice CountryOffice { get; set; }
        public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }
    }
}
