//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class CountryOffice
    {
        public CountryOffice()
        {
            this.Cities = new HashSet<City>();
            this.EmployeeLocations = new HashSet<EmployeeLocation>();
            this.Projects = new HashSet<Project>();
            this.Holidays = new HashSet<Holiday>();
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid CountryOfficeID { get; set; }
        public string CountryName { get; set; }
        public string LicenseKey { get; set; }
    
        public virtual ICollection<City> Cities { get; set; }
        public virtual ICollection<EmployeeLocation> EmployeeLocations { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
