//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid DepartmentID { get; set; }
        public string DepartmentNameAr { get; set; }
        public string DepartmentCode { get; set; }
        public string DepartmentNameEn { get; set; }
        public Nullable<System.DateTime> ActiveFromDate { get; set; }
        public Nullable<bool> ISActive { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
