//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaf
    {
        public System.Guid EmployeeLeaveID { get; set; }
        public System.Guid EmpId { get; set; }
        public System.Guid LeaveTypeID { get; set; }
        public Nullable<decimal> BalanceLeaves { get; set; }
        public Nullable<decimal> IssuedLeaves { get; set; }
        public Nullable<decimal> TotalLeaves { get; set; }
        public Nullable<int> Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<decimal> PostponedLeave { get; set; }
    
        public virtual LeaveType LeaveType { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
