//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.EmployeeHoildays = new HashSet<EmployeeHoilday>();
            this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
            this.EmployeeProjects = new HashSet<EmployeeProject>();
            this.LogTables = new HashSet<LogTable>();
            this.TimeSheetMasters = new HashSet<TimeSheetMaster>();
            this.Weekends = new HashSet<Weekend>();
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
        }
    
        public System.Guid EmployeeID { get; set; }
        public Nullable<System.Guid> UserID { get; set; }
        public string FirstNameAr { get; set; }
        public string SecondNameAr { get; set; }
        public string ThirdNameAr { get; set; }
        public string LastNameAr { get; set; }
        public string FirstNameEn { get; set; }
        public string SecondNameEn { get; set; }
        public string ThirdNameEn { get; set; }
        public string LastNameEn { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<bool> MaritalStatus { get; set; }
        public Nullable<System.DateTime> HireDate { get; set; }
        public Nullable<System.Guid> OfficeLocationID { get; set; }
        public Nullable<System.Guid> DepartmentID { get; set; }
        public Nullable<System.Guid> JobID { get; set; }
        public Nullable<bool> EmployeeStatus { get; set; }
        public Nullable<System.Guid> SupervisorID { get; set; }
        public string Email { get; set; }
        public Nullable<System.Guid> AlternativeSupervisorID { get; set; }
        public Nullable<System.DateTime> AltFromDate { get; set; }
        public Nullable<System.DateTime> AltEndDate { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public Nullable<System.DateTime> Termination_Date { get; set; }
        public string Termination_Reason { get; set; }
        public string Comments { get; set; }
        public Nullable<decimal> LeaveBalacneAtTermination { get; set; }
        public Nullable<bool> IsTerminated { get; set; }
        public string Gender { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual CountryOffice CountryOffice { get; set; }
        public virtual Department Department { get; set; }
        public virtual EmployeeLocation EmployeeLocation { get; set; }
        public virtual JobType JobType { get; set; }
        public virtual ICollection<EmployeeHoilday> EmployeeHoildays { get; set; }
        public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual ICollection<LogTable> LogTables { get; set; }
        public virtual ICollection<TimeSheetMaster> TimeSheetMasters { get; set; }
        public virtual ICollection<Weekend> Weekends { get; set; }
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
    }
}
