//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLocation
    {
        public EmployeeLocation()
        {
            this.Holidays = new HashSet<Holiday>();
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid LocationID { get; set; }
        public string City { get; set; }
        public string Country { get; set; }
        public string LocationName { get; set; }
        public Nullable<System.Guid> CityID { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
    
        public virtual City City1 { get; set; }
        public virtual CountryOffice CountryOffice { get; set; }
        public virtual ICollection<Holiday> Holidays { get; set; }
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
