//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeaveRequest
    {
        public System.Guid EmployeeLeaveRequestID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.Guid> LeaveTypeID { get; set; }
        public string LeaveReason { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public Nullable<int> ActualDate { get; set; }
        public Nullable<int> AssignedDate { get; set; }
        public string LeaveDetectionReason { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> HalfDay { get; set; }
        public Nullable<bool> Cancel { get; set; }
        public Nullable<System.Guid> LeaveBetweenThisAndNextYearID { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LeaveType LeaveType { get; set; }
    }
}
