//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class JobType
    {
        public JobType()
        {
            this.Employees = new HashSet<Employee>();
        }
    
        public System.Guid JobTypeID { get; set; }
        public string JobTypeName { get; set; }
        public string JobTypeNameAr { get; set; }
        public string JobCode { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual ICollection<Employee> Employees { get; set; }
    }
}
