//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveType
    {
        public LeaveType()
        {
            this.EmployeeLeaves = new HashSet<EmployeeLeaf>();
            this.EmployeeLeaveRequests = new HashSet<EmployeeLeaveRequest>();
        }
    
        public System.Guid LeaveTypeID { get; set; }
        public string LeaveTypeName { get; set; }
        public string LeaveTypeColor { get; set; }
        public string LeaveTypeCode { get; set; }
        public Nullable<decimal> DefaultLeaves { get; set; }
        public Nullable<bool> WillHolidaysCount { get; set; }
    
        public virtual ICollection<EmployeeLeaf> EmployeeLeaves { get; set; }
        public virtual ICollection<EmployeeLeaveRequest> EmployeeLeaveRequests { get; set; }
    }
}
