//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogTable
    {
        public System.Guid LogID { get; set; }
        public Nullable<System.Guid> ItemID { get; set; }
        public string Operation { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public string Notes { get; set; }
    
        public virtual Employee Employee { get; set; }
    }
}
