//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notification
    {
        public System.Guid NotificationID { get; set; }
        public Nullable<System.Guid> EmployeeID { get; set; }
        public string Message { get; set; }
        public Nullable<System.DateTime> NotinficationTime { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string Url { get; set; }
    }
}
