//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class Project
    {
        public Project()
        {
            this.EmployeeProjects = new HashSet<EmployeeProject>();
        }
    
        public System.Guid ProjectId { get; set; }
        public string ProjectName { get; set; }
        public Nullable<System.Guid> CountryID { get; set; }
        public string ProjectNumber { get; set; }
        public string ProjectNameAr { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
    
        public virtual ICollection<EmployeeProject> EmployeeProjects { get; set; }
        public virtual CountryOffice CountryOffice { get; set; }
    }
}
