//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeSheetMaster
    {
        public TimeSheetMaster()
        {
            this.TimeSheets = new HashSet<TimeSheet>();
        }
    
        public System.Guid TimeSheetMasterID { get; set; }
        public Nullable<System.Guid> EmpID { get; set; }
        public string Month { get; set; }
        public string Year { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsSubmit { get; set; }
        public string Status { get; set; }
        public Nullable<int> MonthNumber { get; set; }
    
        public virtual ICollection<TimeSheet> TimeSheets { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
